<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PipelineCore.Abstractions/PipelineCore.Abstractions.csproj" />
    <ProjectReference Include="../PipelineCore.Configuration/PipelineCore.Configuration.csproj" />
    <ProjectReference Include="../PipelineCore.Domain/PipelineCore.Domain.csproj" />
    <ProjectReference Include="../PipelineCore.Engine/PipelineCore.Engine.csproj" />
  </ItemGroup>

</Project>
